import React from 'react';
import {Link} from 'react-router-dom';

const LoremIpsum = (props) => <div style={{
	width: 50 + 'em',
	marginLeft: 'auto',
	marginRight: 'auto'
}}>
	<Link to={'/'}>Home</Link>
	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultricies integer quis auctor elit sed vulputate mi sit amet. Sed arcu non odio euismod. Iaculis urna id volutpat lacus. Porta non pulvinar neque laoreet suspendisse interdum. Bibendum ut tristique et egestas quis ipsum suspendisse ultrices. Habitant morbi tristique senectus et netus. Amet mauris commodo quis imperdiet. Augue eget arcu dictum varius duis at consectetur lorem donec. Sit amet consectetur adipiscing elit ut aliquam purus sit amet. Duis tristique sollicitudin nibh sit amet commodo nulla. Viverra justo nec ultrices dui sapien eget mi proin. Ornare arcu odio ut sem nulla. Tincidunt eget nullam non nisi. Et tortor consequat id porta nibh. Cras ornare arcu dui vivamus arcu felis bibendum. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Tincidunt dui ut ornare lectus sit amet. Nulla facilisi etiam dignissim diam quis enim lobortis scelerisque. Faucibus pulvinar elementum integer enim neque.</p>
	<p>Rutrum quisque non tellus orci ac. Quis lectus nulla at volutpat diam ut venenatis tellus. Posuere ac ut consequat semper viverra nam libero justo. Turpis massa tincidunt dui ut. In tellus integer feugiat scelerisque varius morbi. Tellus id interdum velit laoreet id donec. Cursus in hac habitasse platea dictumst. Quis imperdiet massa tincidunt nunc pulvinar sapien. Pulvinar proin gravida hendrerit lectus. Viverra tellus in hac habitasse platea dictumst.</p>
	<p>Pellentesque elit eget gravida cum sociis natoque penatibus et magnis. A arcu cursus vitae congue mauris rhoncus aenean. Arcu cursus euismod quis viverra nibh cras pulvinar mattis nunc. Vel risus commodo viverra maecenas accumsan lacus vel. Cursus vitae congue mauris rhoncus aenean. Nulla at volutpat diam ut venenatis tellus in. Augue interdum velit euismod in pellentesque massa placerat. Nibh mauris cursus mattis molestie a iaculis at erat pellentesque. Risus feugiat in ante metus dictum at tempor. Aliquam etiam erat velit scelerisque in dictum non consectetur. Posuere ac ut consequat semper viverra nam. Eleifend donec pretium vulputate sapien nec sagittis. Pellentesque dignissim enim sit amet. Congue nisi vitae suscipit tellus.</p>
	<p>Accumsan in nisl nisi scelerisque eu. Molestie nunc non blandit massa. Condimentum vitae sapien pellentesque habitant morbi. Consectetur purus ut faucibus pulvinar elementum integer enim neque. Metus vulputate eu scelerisque felis imperdiet. Ultrices dui sapien eget mi proin sed libero enim sed. Tristique senectus et netus et malesuada fames. Viverra justo nec ultrices dui sapien eget mi proin sed. Viverra nibh cras pulvinar mattis nunc sed blandit libero. Pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. Facilisis magna etiam tempor orci eu lobortis elementum. Egestas pretium aenean pharetra magna ac placerat vestibulum lectus mauris. Nec feugiat nisl pretium fusce id velit ut tortor pretium. Urna et pharetra pharetra massa. Adipiscing tristique risus nec feugiat in fermentum posuere. Lacus sed viverra tellus in hac habitasse. Tempus quam pellentesque nec nam. Egestas tellus rutrum tellus pellentesque eu tincidunt. At quis risus sed vulputate odio ut enim blandit.</p>
	<p>Aliquam sem fringilla ut morbi tincidunt augue interdum velit. Fermentum posuere urna nec tincidunt praesent semper feugiat. Non tellus orci ac auctor augue mauris augue. At tempor commodo ullamcorper a lacus vestibulum sed arcu. Dui id ornare arcu odio ut sem nulla. Sem et tortor consequat id porta nibh venenatis cras sed. Nisl pretium fusce id velit ut tortor pretium viverra. Elementum tempus egestas sed sed risus pretium. Condimentum vitae sapien pellentesque habitant. Odio tempor orci dapibus ultrices in iaculis nunc sed augue. Cursus euismod quis viverra nibh cras pulvinar. Nunc consequat interdum varius sit amet. Nulla porttitor massa id neque aliquam vestibulum morbi blandit cursus. Tellus at urna condimentum mattis pellentesque. Donec ac odio tempor orci dapibus ultrices in. Metus aliquam eleifend mi in nulla posuere sollicitudin. Odio tempor orci dapibus ultrices in iaculis nunc sed augue.</p>
	<p>Adipiscing elit ut aliquam purus sit amet luctus. Id faucibus nisl tincidunt eget nullam non. Integer feugiat scelerisque varius morbi enim. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam. Turpis massa tincidunt dui ut ornare lectus sit. Sed ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Gravida in fermentum et sollicitudin. Consectetur lorem donec massa sapien faucibus et. Nunc faucibus a pellentesque sit amet porttitor eget dolor. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Neque viverra justo nec ultrices dui sapien eget. Non tellus orci ac auctor. Ipsum dolor sit amet consectetur adipiscing elit pellentesque.</p>
	<p>Pharetra convallis posuere morbi leo urna molestie at. Diam ut venenatis tellus in. Sem nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Pretium quam vulputate dignissim suspendisse in est ante in. Pellentesque id nibh tortor id aliquet lectus. Nunc aliquet bibendum enim facilisis gravida neque convallis a. Dictum varius duis at consectetur lorem donec. Feugiat pretium nibh ipsum consequat nisl vel pretium. In hendrerit gravida rutrum quisque non. Augue neque gravida in fermentum et sollicitudin ac orci phasellus. Nisi quis eleifend quam adipiscing. Integer enim neque volutpat ac tincidunt vitae semper quis. Quam elementum pulvinar etiam non quam lacus suspendisse. Cursus euismod quis viverra nibh cras pulvinar. Rhoncus urna neque viverra justo nec ultrices dui sapien eget.</p>
	<p>Mauris nunc congue nisi vitae suscipit tellus. Arcu non sodales neque sodales ut etiam sit amet. Sit amet consectetur adipiscing elit. At ultrices mi tempus imperdiet nulla malesuada pellentesque elit. Quis imperdiet massa tincidunt nunc pulvinar sapien et. Et pharetra pharetra massa massa. In iaculis nunc sed augue lacus viverra. Faucibus purus in massa tempor nec feugiat nisl pretium. Vitae justo eget magna fermentum iaculis eu non diam. Elit at imperdiet dui accumsan sit. Scelerisque purus semper eget duis at tellus at urna. Integer quis auctor elit sed vulputate mi sit amet. Ac turpis egestas sed tempus urna et pharetra. Quam elementum pulvinar etiam non quam lacus suspendisse. Dolor magna eget est lorem ipsum. Nisl rhoncus mattis rhoncus urna neque. Et leo duis ut diam quam nulla porttitor massa. Pretium vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae. Maecenas accumsan lacus vel facilisis volutpat est velit egestas. Pulvinar etiam non quam lacus suspendisse faucibus interdum posuere.</p>
	<p>Scelerisque mauris pellentesque pulvinar pellentesque habitant. Pulvinar sapien et ligula ullamcorper malesuada proin libero nunc consequat. Laoreet suspendisse interdum consectetur libero id faucibus nisl. Egestas pretium aenean pharetra magna ac placerat vestibulum lectus mauris. Mattis pellentesque id nibh tortor id. Imperdiet proin fermentum leo vel orci porta non pulvinar neque. Viverra mauris in aliquam sem. Tortor aliquam nulla facilisi cras. Amet dictum sit amet justo donec enim diam vulputate. Natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Auctor neque vitae tempus quam pellentesque nec. Quis commodo odio aenean sed adipiscing diam. At tempor commodo ullamcorper a lacus vestibulum sed. Habitasse platea dictumst vestibulum rhoncus est. Imperdiet dui accumsan sit amet nulla facilisi morbi tempus iaculis. Gravida in fermentum et sollicitudin ac orci phasellus. Est ullamcorper eget nulla facilisi etiam dignissim diam quis enim.</p>
	<p>Risus in hendrerit gravida rutrum quisque non tellus orci ac. Scelerisque fermentum dui faucibus in. Nisl purus in mollis nunc sed id. Eu non diam phasellus vestibulum lorem sed. Mauris in aliquam sem fringilla ut morbi tincidunt. Elementum eu facilisis sed odio. Et ultrices neque ornare aenean euismod elementum nisi quis eleifend. Sit amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Cursus sit amet dictum sit amet justo donec enim. Duis ut diam quam nulla porttitor massa id neque aliquam. Consequat semper viverra nam libero justo laoreet sit.</p>
	<p>Lectus proin nibh nisl condimentum. Nisl suscipit adipiscing bibendum est ultricies. Id porta nibh venenatis cras sed. Egestas congue quisque egestas diam in arcu cursus. Eu sem integer vitae justo eget magna fermentum iaculis. Nisi porta lorem mollis aliquam ut porttitor leo a. Et magnis dis parturient montes nascetur ridiculus mus mauris vitae. Quisque sagittis purus sit amet volutpat consequat mauris nunc congue. Ac placerat vestibulum lectus mauris ultrices eros in cursus. Iaculis eu non diam phasellus. Quam viverra orci sagittis eu volutpat odio facilisis mauris. Velit euismod in pellentesque massa placerat. Mi sit amet mauris commodo. Non sodales neque sodales ut etiam sit amet nisl purus. Ut eu sem integer vitae justo eget. Mi sit amet mauris commodo quis imperdiet massa tincidunt nunc. Adipiscing tristique risus nec feugiat in fermentum posuere urna. Hendrerit dolor magna eget est. Ligula ullamcorper malesuada proin libero nunc consequat interdum. Ac tortor vitae purus faucibus ornare suspendisse.</p>
	<p>Sed euismod nisi porta lorem mollis aliquam ut. Turpis egestas integer eget aliquet nibh. Diam sit amet nisl suscipit adipiscing bibendum est. Nullam eget felis eget nunc lobortis mattis aliquam faucibus purus. In fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Cras adipiscing enim eu turpis egestas pretium. Blandit libero volutpat sed cras ornare. Lectus vestibulum mattis ullamcorper velit. Faucibus et molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Duis convallis convallis tellus id interdum velit laoreet. Sed arcu non odio euismod lacinia at quis risus sed. Turpis massa sed elementum tempus egestas sed sed. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat. Velit egestas dui id ornare arcu odio ut. Nullam non nisi est sit amet facilisis.</p>
	<p>Sit amet cursus sit amet. Sed blandit libero volutpat sed cras ornare arcu. Feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Tortor consequat id porta nibh. Enim nec dui nunc mattis enim ut tellus elementum sagittis. Ultrices tincidunt arcu non sodales neque. Urna et pharetra pharetra massa massa. Eu non diam phasellus vestibulum lorem sed risus. Consectetur adipiscing elit ut aliquam purus sit amet luctus venenatis. Ridiculus mus mauris vitae ultricies leo integer malesuada. Nunc sed blandit libero volutpat. Convallis aenean et tortor at risus viverra. Scelerisque varius morbi enim nunc faucibus a pellentesque. Purus sit amet luctus venenatis. Amet nisl suscipit adipiscing bibendum est ultricies. Tincidunt lobortis feugiat vivamus at augue eget arcu dictum varius.</p>
	<p>Et malesuada fames ac turpis egestas maecenas pharetra. Malesuada fames ac turpis egestas. Etiam tempor orci eu lobortis elementum nibh tellus. Ut tristique et egestas quis ipsum. Laoreet id donec ultrices tincidunt arcu non sodales neque sodales. Nam libero justo laoreet sit amet. Dignissim sodales ut eu sem integer vitae. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra justo. Ornare arcu dui vivamus arcu. Augue interdum velit euismod in pellentesque. Nec ultrices dui sapien eget mi proin. Risus in hendrerit gravida rutrum quisque. Fringilla urna porttitor rhoncus dolor purus non enim. Amet venenatis urna cursus eget nunc scelerisque. Integer feugiat scelerisque varius morbi. Varius morbi enim nunc faucibus a pellentesque sit amet. Etiam tempor orci eu lobortis.</p>
	<p>At elementum eu facilisis sed odio. Pretium lectus quam id leo in vitae turpis. Arcu dui vivamus arcu felis. Proin fermentum leo vel orci porta non pulvinar neque laoreet. Etiam erat velit scelerisque in dictum non consectetur. Sit amet nisl purus in mollis. Velit scelerisque in dictum non consectetur a erat. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Nec feugiat nisl pretium fusce id velit ut tortor. Amet venenatis urna cursus eget nunc scelerisque viverra. Lobortis feugiat vivamus at augue eget. Dignissim diam quis enim lobortis scelerisque fermentum dui faucibus. Commodo nulla facilisi nullam vehicula ipsum. Est ullamcorper eget nulla facilisi. Velit egestas dui id ornare arcu odio ut.</p>
</div>;

export default LoremIpsum;