server:
  hostname: "localhost"
  port: 443
tls:
  key: "C:\\Users\\DaCO9\\certificates\\localhost.key"
  cert: "C:\\Users\\DaCO9\\certificates\\localhost.crt"
psql:
  hostname: "127.0.0.1"
  port: 5432
