---
version: "3"

services:
  asset-bundle:
    image: "node:9.6.1"
    volumes:
      - "./:/app"
    working_dir: "/app"
    command: "./node_modules/.bin/webpack --config webpack.config.js"
  server:
    image: "node:9.6.1"
    depends_on:
      - redis
      - psql
    volumes:
      - "./:/app"
    working_dir: "/app"
    ports:
      - "443:443"
    restart: unless-stopped
    command: "node --experimental-modules --harmony-dynamic-import ./server/index.mjs"
  socket:
    image: "node:9.6.1"
    depends_on:
      - redis
      - psql
    volumes:
      - "./:/app"
    ports:
      - "8443:8443"
    restart: unless-stopped
    command: "node --experimental-modules --harmony-dynamic-import ./socker/index.mjs"
  redis:
    image: "redis:4.0.6"
    expose:
      - "6379"
    restart: unless-stopped
  psql:
    image: "postgres:10.2"
    environment:
      POSTGRES_PASSWORD: "turnin_password"
    expose:
      - "5432"

...
