---
version: "3"

services:
  asset-bundle:
    image: "node:9.10.1"
    volumes:
      - "./:/app"
    working_dir: "/app"
    environment:
      - "NODE_ENV=development"
    command: "./node_modules/.bin/webpack --config webpack.config.js --watch"
  server:
    image: "node:9.10.1"
    depends_on:
      - redis
      - psql
    volumes:
      - "./:/app"
      - "../_configs/turnin:/etc/turnin"
      - "../_data/turnin:/var/lib/turnin/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    working_dir: "/app"
    environment:
      - "NODE_ENV=development"
    ports:
      - "443:443"
    restart: unless-stopped
    command: "node ./server/index.js --c-psql.hostname psql --c-redis.hostname redis"
  worker:
    image: "node:9.10.1"
    depends_on:
      - redis
      - psql
    volumes:
      - "./:/app"
      - "../_configs/turnin:/etc/turnin"
      - "../_data/turnin:/var/lib/turnin/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    working_dir: "/app"
    environment:
      - "NODE_ENV=development"
    expose:
      - "443"
    restart: "unless-stopped"
    command: "node ./worker/index.js --c-psql.hostname psql --c-redis.hostname redis"
  redis:
    image: "redis:4.0.6"
    expose:
      - "6379"
    restart: unless-stopped
  psql:
    build: ./psql/
    environment:
      POSTGRES_PASSWORD: "password"
    expose:
      - "5432"

...
