---
version: "3.1"

services:
  # asset-bundle:
  #   image: "node:10.0.0"
  #   volumes:
  #     - "./:/app"
  #   working_dir: "/app"
  #   environment:
  #     - "NODE_ENV=development"
  #   command: "./node_modules/.bin/webpack --config webpack.config.js --watch"
  psql:
    image: "postgres:11.0"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "turnin"
    ports:
      - "5432:5432"
...
