CREATE USER turnin;

CREATE DATABASE turnin;

GRANT ALL PRIVILEGES ON DATABASE turnin TO turnin;
ALTER USER turnin WITH PASSWORD 'turnin_password';

ALTER DEFAULT PRIVILEGES FOR USER turnin IN SCHEMA public GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO turnin;

