\connect turnin

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO turnin;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO turnin;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO turnin;